extends SceneTree
## M42-C003 V03 runtime evidence: renders the REAL Home (current background, SCRUBBY_SCALE
## 1.612, HomeScrubbyHero) and captures what the runtime actually draws. The hero is
## driven through its deterministic step() seam, so every captured frame is a true render
## of that animation time (frame-accurate runtime capture, not a screen recording).
## Needs a rendering driver (run WITHOUT --headless):
##   godot --path . -s res://tests/tools/m42_c003_animation_evidence.gd -- <evidence_dir> <frames_dir>
## Writes to <evidence_dir>: viewport captures, true-scale transition strips, Reduced
## Effects capture, screen-space collision + helper reports, lifecycle report.
## Writes per-gesture runtime frame sequences (24 fps) to <frames_dir> for animation assembly.

const AppState = preload("res://scripts/app/app_state.gd")
const HomeScreenScene = preload("res://scenes/ui/home/home_screen.tscn")
const LocalCalendar = preload("res://scripts/economy/local_calendar.gd")
const Suite = preload("res://tests/m42_c003_scrubby_animation.gd")

const CAPTURE_FPS := 24.0
const GESTURES := ["wave", "bow", "turn", "full_turn"]

var _out := ""
var _frames := ""

func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	_out = ProjectSettings.globalize_path(args[0] if args.size() > 0 else "user://m42_c003_evidence")
	_frames = ProjectSettings.globalize_path(args[1] if args.size() > 1 else "user://m42_c003_frames")
	DirAccess.make_dir_recursive_absolute(_out)
	DirAccess.make_dir_recursive_absolute(_out + "/transition_strips")
	DirAccess.make_dir_recursive_absolute(_out + "/viewports")
	DirAccess.make_dir_recursive_absolute(_frames)
	var save_path := "user://m42_c003_evidence_%d.save" % Time.get_ticks_usec()
	var now := 1790000000
	var clock := func(): return now
	var app = AppState.new(save_path, clock, LocalCalendar.offset_provider(clock, 0))
	var e = app.economy
	e.wallet.credit("scrub_bucks", 1250)
	e.wallet.credit("bot_parts", 158)
	e.hearts.consume()
	e.gift.add_streak_sb("snapshot_gift", 60)
	e.streak.process_first_clear_win(1)
	e.streak.process_first_clear_win(2)
	await process_frame
	var report: Array = ["# M42-C003 V03 live-node screen-space collision report", "",
		"Generated by `tests/tools/m42_c003_animation_evidence.gd` from the live Home (zero safe-area insets). For every one of the 63 frames the gesture TextureRect's actual placement is used; opaque = alpha > 0.5 texel centres inside the live control rect. Rects are (x, y, w, h) in viewport px.", ""]
	var helper: Array = ["# M42-C003 V03 helper overlap / z-order report", "",
		"The left/right helper bots are baked into the Home background (HOME-121). `Layer_characters` (shade, Art_scrubby, HomeScrubbyHero/Art_scrubby_gesture) is a later child of `Background`, so Scrubby always draws IN FRONT of both helpers; no helper fade/hide is needed or implemented. Owner V03: helper overlap is warning-only. Counts = opaque gesture texels inside the helper's mapped catalog rect.", "",
		"| Viewport | Gesture | Frames overlapping left helper | Max texels | Frames overlapping right helper | Max texels |", "|---|---|---:|---:|---:|---:|"]
	for vp in Suite.VIEWPORTS:
		var r = await _home(vp, app)
		var home = r[1]
		var hero = r[2]
		_save(r[0], "%s/viewports/home_v03_idle_%dx%d.png" % [_out, vp.x, vp.y])
		hero.start_gesture("wave")
		_step(hero, 0.5)
		await _frame()
		_save(r[0], "%s/viewports/home_v03_wave_mid_%dx%d.jpg" % [_out, vp.x, vp.y])
		_step(hero, 2.0)
		var m: Dictionary = Suite.measure_frames(home)
		report.append("## %dx%d" % [vp.x, vp.y])
		report.append("")
		report.append("- Gesture TextureRect: %s (one rect for all frames; %.4f viewport px per animation px)" % [str(m["gesture_rect"]), m["px"]])
		report.append("- Art_scrubby (HOME-026) rect: %s" % str(_local(home, "Art_scrubby")))
		report.append("- Union of all 63 frames' used rects: %s; world clip %s; frames clipped: %d" % [str(m["union"]), str(_local(home, "Background")), (m["clip_out"] as Array).size()])
		report.append("")
		report.append("| Hard blocker | Rect | Opaque gesture texels (63 frames) |")
		report.append("|---|---|---:|")
		for n in Suite.HARD:
			var total := 0
			for k in m["hard"]:
				if String(k).begins_with(n + ":"):
					total += int(m["hard"][k])
			report.append("| %s | %s | %d |" % [n, str(_local(home, n)), total])
		report.append("")
		for g in GESTURES:
			var lf := 0
			var lm := 0
			var rf := 0
			var rm := 0
			for k in m["helpers"]:
				var parts := String(k).split(":")
				if parts[1].substr(0, parts[1].length() - 3) != g:
					continue
				if parts[0] == "left":
					lf += 1
					lm = maxi(lm, int(m["helpers"][k]))
				else:
					rf += 1
					rm = maxi(rm, int(m["helpers"][k]))
			helper.append("| %dx%d | %s | %d | %d | %d | %d |" % [vp.x, vp.y, g, lf, lm, rf, rm])
		r[0].free()
		await process_frame
	_write("screen_space_collision_report.md", report.slice(0, report.size() - 1) if report.back() == "" else report)
	_write("helper_overlap_report.md", helper)
	await _strips_and_sequences(app)
	await _reduced(app)
	await _lifecycle(app)
	for suffix in ["", ".bak", ".tmp"]:
		if FileAccess.file_exists(save_path + suffix):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path + suffix))
	quit(0)

func _home(size: Vector2i, app) -> Array:
	var sub := SubViewport.new()
	sub.size = size
	sub.disable_3d = true
	sub.transparent_bg = false
	sub.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	get_root().add_child(sub)
	var home = HomeScreenScene.instantiate()
	sub.add_child(home)
	home.bind(app)
	home.get_region("SafeAreaRoot").set_synthetic_insets(0, 0, 0, 0)
	for _i in range(12):
		await process_frame
	home.refresh()
	var hero = home.get_region("HomeScrubbyHero")
	hero.set_process(false)
	hero.set_rng_seed(42)
	# Settle at idle phase 0 (a finished gesture resets idle exactly).
	hero.start_gesture("bow")
	_step(hero, 2.0)
	for _i in range(6):
		await process_frame
	return [sub, home, hero]

func _step(hero, seconds: float) -> void:
	var dt := 1.0 / 240.0
	for _i in range(int(round(seconds / dt))):
		hero.step(dt)

func _frame() -> void:
	for _i in range(3):
		await process_frame

func _local(home, n: String) -> Rect2:
	var r: Rect2 = home.get_region(n).get_global_rect()
	r.position -= home.global_position
	return r

func _save(sub: SubViewport, path: String) -> Image:
	var img := sub.get_texture().get_image()
	if path.ends_with(".jpg"):
		img.save_jpg(path, 0.92)
	else:
		img.save_png(path)
	print("SNAPSHOT ", path)
	return img

## True-scale (1:1 viewport px) HOME -> gesture frames -> HOME strips at 1080x2160, and
## 24 fps runtime sequences (idle -> gesture -> idle) for every gesture.
func _strips_and_sequences(app) -> void:
	var r = await _home(Vector2i(1080, 2160), app)
	var home = r[1]
	var hero = r[2]
	var m: Dictionary = Suite.measure_frames(home)
	var crop := Rect2i((m["union"] as Rect2).merge(_local(home, "Art_scrubby")).grow(12))
	crop = crop.intersection(Rect2i(0, 0, 1080, 2160))
	for g in GESTURES:
		var tiles: Array = []
		tiles.append(_save(r[0], "%s/_home.png" % _frames).get_region(crop))
		var n: int = (hero.get_set()["textures"][g] as Array).size()
		hero.start_gesture(g)
		for i in n:
			hero.step(0.0)
			await _frame()
			tiles.append(r[0].get_texture().get_image().get_region(crop))
			_step(hero, 1.0 / 12.0)
		_step(hero, 0.05)
		await _frame()
		tiles.append(r[0].get_texture().get_image().get_region(crop))
		_grid(tiles, crop.size, "%s/transition_strips/%s.jpg" % [_out, g])
		# 24 fps runtime sequence: 0.5 s idle, gesture, 0.5 s idle.
		var dir := "%s/%s" % [_frames, g]
		DirAccess.make_dir_recursive_absolute(dir)
		var k := 0
		var dt := 1.0 / CAPTURE_FPS
		for phase in ["pre", "gesture", "post"]:
			if phase == "gesture":
				hero.start_gesture(g)
			var t := 0.0
			var limit: float = 0.5 if phase != "gesture" else hero.gesture_duration(g)
			while t < limit - 1e-6:
				await _frame()
				r[0].get_texture().get_image().get_region(crop).save_png("%s/%03d.png" % [dir, k])
				k += 1
				hero.step(dt)
				t += dt
		print("SEQUENCE ", g, " frames=", k)
	r[0].free()
	await process_frame

func _grid(tiles: Array, cell: Vector2i, path: String) -> void:
	var cols := 6
	var rows := int(ceil(float(tiles.size()) / cols))
	var img := Image.create(cols * cell.x + (cols - 1) * 8, rows * cell.y + (rows - 1) * 8, false, Image.FORMAT_RGBA8)
	img.fill(Color(1, 1, 1))
	for i in tiles.size():
		var t: Image = tiles[i]
		t.convert(Image.FORMAT_RGBA8)
		img.blit_rect(t, Rect2i(Vector2i.ZERO, cell), Vector2i((i % cols) * (cell.x + 8), (i / cols) * (cell.y + 8)))
	img.save_jpg(path, 0.92)
	print("STRIP ", path, " tiles=", tiles.size())

func _reduced(app) -> void:
	var r = await _home(Vector2i(1080, 2160), app)
	var hero = r[2]
	var counts_before: Dictionary = hero.get_state()["counts"].duplicate()
	app.effects.set_reduced(true)
	var hashes := {}
	var first: Image = null
	for i in range(12):
		hero.start_gesture(Suite.COUNTS.keys()[i % 4])
		_step(hero, 0.5)
		await _frame()
		var img: Image = r[0].get_texture().get_image()
		if first == null:
			first = img
		hashes[Marshalls.raw_to_base64(img.get_data()).sha256_text()] = true
	first.save_jpg("%s/reduced_effects_static_1080x2160.jpg" % _out, 0.92)
	_write("reduced_effects_report.md", ["# M42-C003 V03 Reduced Effects capture", "",
		"AppState.effects.set_reduced(true) on a live Home, then 12 attempts to start each gesture in turn with 0.5 s of runtime between renders (6 s total).", "",
		"- Distinct rendered frames: %d (1 = completely static)" % hashes.size(),
		"- Gesture start counts before ON %s -> after 12 attempts %s (start_gesture refused while reduced)" % [str(counts_before), str(hero.get_state()["counts"])],
		"- Idle squash: %s (identity)" % str(hero.get_idle_squash()),
		"- Capture: `reduced_effects_static_1080x2160.jpg`"])
	app.effects.set_reduced(false)
	r[0].free()
	await process_frame

func _lifecycle(app) -> void:
	var lines: Array = ["# M42-C003 V03 lifecycle stability (20x)", ""]
	var r = await _home(Vector2i(1080, 2160), app)
	var home = r[1]
	var hero = r[2]
	var base_nodes := _count(home)
	var base_conns: int = app.effects.changed.get_connections().size()
	lines.append("| Cycle | Home visible -> hidden -> visible | Nodes | effects.changed connections | Started gestures (cumulative) |")
	lines.append("|---:|---|---:|---:|---|")
	for i in range(20):
		home.visible = false
		_step(hero, 0.5)
		home.visible = true
		_step(hero, 13.0)
		lines.append("| %d | ok | %d | %d | %s |" % [i + 1, _count(home), app.effects.changed.get_connections().size(), str(hero.get_state()["counts"])])
	lines.append("")
	lines.append("Baseline nodes %d, connections %d -> after 20 cycles %d / %d." % [base_nodes, base_conns, _count(home), app.effects.changed.get_connections().size()])
	r[0].free()
	await process_frame
	var before: int = app.effects.changed.get_connections().size()
	var objs := Performance.get_monitor(Performance.OBJECT_COUNT)
	for i in range(20):
		var q = await _home(Vector2i(1080, 2160), app)
		_step(q[2], 7.0)
		q[0].free()
		await process_frame
	await process_frame
	lines.append("20x Home instantiate/bind/free with the same AppState: effects.changed connections %d -> %d; object count delta %d." % [before, app.effects.changed.get_connections().size(), int(Performance.get_monitor(Performance.OBJECT_COUNT) - objs)])
	lines.append("")
	lines.append("No Timer, Tween or per-cycle signal is created by HomeScrubbyHero (it is driven by _process/step only).")
	_write("lifecycle_stability_report.md", lines)

func _count(n: Node) -> int:
	var c := 1
	for ch in n.get_children():
		c += _count(ch)
	return c

func _write(name: String, lines: Array) -> void:
	var f := FileAccess.open(_out + "/" + name, FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")
	f.close()
	print("REPORT ", name)
