extends SceneTree
## M42-C002 owner visual evidence: renders the REAL Home (current 940x1672 background,
## production SCRUBBY_SCALE 1.612) at the four required viewports, a 1080x2160 before
## (1.24) vs after (1.612) montage, and the geometry/collision measurement report.
## Needs a rendering driver (run WITHOUT --headless):
##   godot --path . -s res://tests/tools/m42_c002_scale_evidence.gd -- <out_dir>
## The "before" frame re-places the same hero node at the prior 1.24 canonical geometry
## (same soles anchor) after layout; nothing is written to approved art paths.

const AppState = preload("res://scripts/app/app_state.gd")
const HomeScreenScene = preload("res://scenes/ui/home/home_screen.tscn")
const LocalCalendar = preload("res://scripts/economy/local_calendar.gd")
const HS = preload("res://scripts/ui/home/home_screen.gd")
const Suite = preload("res://tests/m42_c002_scrubby_scale.gd")

func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	var out_dir: String = args[0] if args.size() > 0 else "user://m42_c002_evidence"
	out_dir = out_dir if out_dir.is_absolute_path() else ProjectSettings.globalize_path(out_dir)
	DirAccess.make_dir_recursive_absolute(out_dir)
	var now := 1790000000
	var clock := func(): return now
	var save_path := "user://m42_c002_evidence_%d.save" % Time.get_ticks_usec()
	var app = AppState.new(save_path, clock, LocalCalendar.offset_provider(clock, 0))
	# Same representative state as tests/tools/home_snapshot.gd (temp save, deleted below).
	var e = app.economy
	e.wallet.credit("scrub_bucks", 1250)
	e.wallet.credit("bot_parts", 158)
	e.hearts.consume()
	e.gift.add_streak_sb("snapshot_gift", 60)
	e.streak.process_first_clear_win(1)
	e.streak.process_first_clear_win(2)
	e.collection.add_copies(e.collection.all_card_ids()[0], 3)
	await process_frame
	var rows: Array = []
	var before: Image = null
	var after: Image = null
	for size in Suite.VIEWPORTS:
		var sub := SubViewport.new()
		sub.size = size
		sub.disable_3d = true
		sub.transparent_bg = false
		sub.render_target_update_mode = SubViewport.UPDATE_ALWAYS
		get_root().add_child(sub)
		var home = HomeScreenScene.instantiate()
		sub.add_child(home)
		home.bind(app)
		home.get_region("SafeAreaRoot").set_synthetic_insets(0, 0, 0, 0)
		for _i in range(12):
			await process_frame
		home.refresh()
		for _i in range(6):
			await process_frame
		var img := _save(sub, "%s/home_scrubby_1612_%dx%d.png" % [out_dir, size.x, size.y])
		rows.append(Suite.measure(home))
		if size == Vector2i(1080, 2160):
			after = img
			var sc: TextureRect = home.get_region("Art_scrubby")
			var r := sc.get_rect()
			var old: Dictionary = Suite.canonical_for(home, Suite.OLD_SCALE)
			var s: float = home.get_world_transform()["scale"]
			var feet: Vector2 = home.get_world()["scrubby_feet_anchor"]
			var k: float = old["k"]
			sc.position = home.world_to_screen(Vector2(feet.x - (HS.SCRUBBY_VISIBLE_BBOX.get_center().x) * k, feet.y - HS.SCRUBBY_FEET_Y * k))
			sc.size = r.size * (Suite.OLD_SCALE / HS.SCRUBBY_SCALE)
			for _i in range(3):
				await process_frame
			before = _save(sub, "%s/home_scrubby_124_before_1080x2160.png" % out_dir)
		sub.queue_free()
		await process_frame
	# Montage: before | 24 px divider | after (both 1080x2160, unscaled).
	var mont := Image.create(1080 * 2 + 24, 2160, false, Image.FORMAT_RGBA8)
	mont.fill(Color(1, 1, 1))
	mont.blit_rect(_rgba(before), Rect2i(0, 0, 1080, 2160), Vector2i(0, 0))
	mont.blit_rect(_rgba(after), Rect2i(0, 0, 1080, 2160), Vector2i(1080 + 24, 0))
	var mp := "%s/home_scrubby_before_124_vs_after_1612_1080x2160.png" % out_dir
	print("SNAPSHOT ", mp, " err=", mont.save_png(mp))
	_report(out_dir, rows)
	for suffix in ["", ".bak", ".tmp"]:
		if FileAccess.file_exists(save_path + suffix):
			DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path + suffix))
	quit(0)

func _rgba(img: Image) -> Image:
	var c := img.duplicate() as Image
	c.convert(Image.FORMAT_RGBA8)
	return c

func _save(sub: SubViewport, path: String) -> Image:
	var img := sub.get_texture().get_image()
	var err := img.save_png(path)
	print("SNAPSHOT ", path, " err=", err, " size=", img.get_size())
	return img

static func _r(r: Rect2) -> String:
	return "(%.1f, %.1f, %.1f, %.1f)" % [r.position.x, r.position.y, r.size.x, r.size.y]

static func _v(v: Vector2) -> String:
	return "(%.2f, %.2f)" % [v.x, v.y]

func _report(out_dir: String, rows: Array) -> void:
	var L: Array = []
	L.append("# M42-C002 — Home Scrubby 1.612 measurement report")
	L.append("")
	L.append("Generated by `tests/tools/m42_c002_scale_evidence.gd` from the live Home scene (current 940x1672 `home_background_whispering_park`, zero safe-area insets). Rects are `(x, y, w, h)`; canvas = world canvas px, screen = viewport px.")
	L.append("")
	L.append("SCRUBBY_SCALE %s (was %s; ratio %.6f). HOME-026 visible bbox %s, soles line y %.0f. Feet anchor (470, 1240); safe box (305, 620, 330, 620).\n" % [str(HS.SCRUBBY_SCALE), str(Suite.OLD_SCALE), HS.SCRUBBY_SCALE / Suite.OLD_SCALE, _r(HS.SCRUBBY_VISIBLE_BBOX), HS.SCRUBBY_FEET_Y])
	L.append("## Geometry\n")
	L.append("| Viewport | World scale | World offset | Old 1.24 visible (screen) | New 1.612 visible (screen) | New visible (canvas) | Soles (screen) | Platform contact (screen) | Error px |")
	L.append("|---|---|---|---|---|---|---|---|---|")
	for m in rows:
		L.append("| %dx%d | %.5f | %s | %s | %s | %s | %s | %s | %.4f |" % [m["viewport"].x, m["viewport"].y, m["world_scale"], _v(m["world_offset"]), _r(m["old_visible_screen"]), _r(m["new_visible_screen"]), _r(m["new_visible_canvas"]), _v(m["feet_screen"]), _v(m["contact_screen"]), (m["feet_screen"] as Vector2).distance_to(m["contact_screen"])])
	L.append("\n## Functional UI collision matrix\n")
	L.append("`bbox` = the hero's rectangular visible bbox intersects the control rect; `opaque px` = HOME-026 texels with alpha > 128 drawn inside the control rect; `clearance` = smallest screen distance from any opaque hero pixel to the rect (searched within 96 px; `>96` = none nearer). All controls draw above the hero layer and the hero/shade/character layer are MOUSE_FILTER_IGNORE.\n")
	L.append("| Viewport | Control | Rect (screen) | bbox | opaque px | clearance px |")
	L.append("|---|---|---|---|---|---|")
	for m in rows:
		for n in Suite.FUNCTIONAL + ["WinStreakRewardTrack", "AdBannerSlot"]:
			var u: Dictionary = m["ui"][n]
			L.append("| %dx%d | %s | %s | %s | %d | %s |" % [m["viewport"].x, m["viewport"].y, n, _r(u["rect"]), "hit" if u["bbox_hit"] else "clear", u["opaque_px"], ("%.1f" % u["clearance"]) if is_finite(u["clearance"]) else ">96"])
	L.append("\n## Baked sign / helper bots\n")
	L.append("| Viewport | Sign rect (screen) | Sign bbox / opaque px | Left bot rect (screen) | Left bot opaque px / covered rect | Right bot rect (screen) | Right bot opaque px | Panels over a bot |")
	L.append("|---|---|---|---|---|---|---|---|")
	for m in rows:
		var lb: Dictionary = m["bots"][0]
		var rb: Dictionary = m["bots"][1]
		L.append("| %dx%d | %s | %s / %d | %s | %d / %s | %s | %d | %s |" % [m["viewport"].x, m["viewport"].y, _r(m["sign"]["rect"]), "hit" if m["sign"]["bbox_hit"] else "clear", m["sign"]["opaque_px"], _r(lb["rect"]), lb["opaque_px"], _r(lb["opaque_rect"]), _r(rb["rect"]), rb["opaque_px"], str((lb["panel_hits"] as Array) + (rb["panel_hits"] as Array))])
	var f := FileAccess.open(out_dir + "/measurement_report.md", FileAccess.WRITE)
	f.store_string("\n".join(L) + "\n")
	f.close()
	print("REPORT ", out_dir + "/measurement_report.md")
