extends Node2D
## ScrubbotVisual — preload this script
## (res://scripts/gameplay/presentation/scrubbot_visual.gd) rather than relying on
## global class_name lookup (AL-001).
##
## M32 — PRESENTATION-ONLY canonical Scrubby travel visual. It is a CHILD of one
## authoritative ScrubbotAgent (M18) and rides that agent's board-local movement
## transform. It NEVER touches gameplay truth: no target selection, no routing, no
## route points, no BoardState, no reservation/claim, no clear timing, no speed. It
## reads NOTHING from gameplay — the parent agent's transform is its only input, and
## all bob/lean/squash motion is applied to a LOCAL child sprite transform, so the
## authoritative agent `position` is never moved, offset or retimed by animation
## (M32 audit §3/§4).
##
## Architecture (M32 prompt §6):
##   ScrubbotAgent (authoritative board-local Node2D position)
##     └── ScrubbotVisual (this — presentation-only local transform)
##           └── body Sprite2D (canonical scrubby_gameplay.png)
##
## The canonical Scrubby gameplay texture is loaded ONCE into a shared static cache
## and reused by every spawned visual (no per-agent Image/Texture decode, M32 audit
## §8). Sizing is in board-local CELL units (the AgentLayer already scales one unit
## to the renderer's cell size), so a responsive relayout rescales the visual for
## free and no screen pixels are baked in.
##
## V01 scope (M32 prompt §4/§8/§10): the DEFAULT Scrubby only, single gameplay body
## pose, no route-dependent mirroring/rotation (no owner directional decision exists).
## The blink and brush-arm layer assets are intentionally NOT composited in V01 —
## they are separate canvases (different sizes/aspect from the gameplay pose) with no
## owner-provided registration offsets, so stacking them would misregister. See
## CLAUDE_LOG_V01.md; travel readability is carried by restrained transform motion.
##
## Missing-asset fail-open (M32 prompt §6): if the shared texture cannot be loaded,
## this visual creates no sprite and does NOT suppress the agent's debug circle, so
## the isolated fallback marker still renders. Gameplay is never affected either way.

## Canonical owner-approved gameplay pose (OWNER_ROBOT_ROSTER_V01 §8). Never mutated,
## never regenerated by M32.
const BODY_TEX_PATH := "res://assets/ui/final/characters/scrubby/scrubby_gameplay.png"

## Apparent Scrubby size in CELL units (the layer scales cells to pixels). Legible but
## intentionally small enough not to blanket a cluster of board cells (M32 prompt §7).
## The larger texture dimension is mapped to this span so the character never crops.
const BODY_SPAN_CELLS := 1.8

## Restrained travel motion tuned for readability, not gameplay (M32 prompt §8). All
## values are in CELL units / cycles-per-second and drive ONLY the local body sprite.
const BOB_AMPLITUDE_CELLS := 0.09
const BOB_HZ := 2.1
const LEAN_RADIANS := 0.06
const LEAN_HZ := 1.7
const SQUASH := 0.05
const SQUASH_HZ := 2.1

# --- shared texture cache (loaded exactly once, reused by every visual) -------
static var _body_tex: Texture2D = null
static var _tex_loaded: bool = false

static func _ensure_texture() -> void:
	if _tex_loaded:
		return
	_tex_loaded = true
	# load() returns the engine-cached resource; assigning it to a static var proves
	# ONE decode shared by all instances (a test asserts every visual's texture is the
	# same object). A missing/failed load leaves _body_tex null -> fail open.
	_body_tex = load(BODY_TEX_PATH) as Texture2D

## Shared canonical gameplay texture for the detached retire echo — the SAME cached
## resource the live travel body uses, so an echo never triggers a second decode
## (M32 audit §8). Returns null when the asset is unavailable (echo fails open).
static func _shared_texture_for_echo() -> Texture2D:
	_ensure_texture()
	return _body_tex

## Test/debug seam: force a texture-missing state to exercise the fail-open fallback
## without deleting the owner asset. Only tests call this.
static func _force_missing_for_test() -> void:
	_tex_loaded = true
	_body_tex = null

var _body: Sprite2D = null
var _base_scale: Vector2 = Vector2.ONE
var _t: float = 0.0

func _ready() -> void:
	_ensure_texture()
	if _body_tex == null:
		# Fail open: no sprite, and the parent keeps its isolated debug-circle fallback.
		return
	_body = Sprite2D.new()
	_body.texture = _body_tex
	_body.centered = true
	# Smooth anti-aliased character art: linear filtering, never nearest (M32 §8/§11).
	_body.texture_filter = CanvasItem.TEXTURE_FILTER_LINEAR
	var longest: float = float(max(_body_tex.get_width(), _body_tex.get_height(), 1))
	var s: float = BODY_SPAN_CELLS / longest
	_base_scale = Vector2(s, s)
	_body.scale = _base_scale
	add_child(_body)
	# Canonical Scrubby is present -> suppress the parent agent's debug circle so the
	# normal production path never draws it (M32 prompt §6, audit §9).
	var p = get_parent()
	if p != null and p.has_method("set_visual_present"):
		p.set_visual_present(true)

func _process(delta: float) -> void:
	animate(delta)

## Advance the presentation-only travel animation by `delta`. Public so tests can drive
## it deterministically with set_process(false). Moves/rotates/squashes ONLY the local
## body sprite — never this node's own position and never the authoritative agent.
func animate(delta: float) -> void:
	if _body == null or not is_instance_valid(_body):
		return
	_t += delta
	var tau := TAU
	_body.position = Vector2(0.0, -sin(_t * BOB_HZ * tau) * BOB_AMPLITUDE_CELLS)
	_body.rotation = sin(_t * LEAN_HZ * tau) * LEAN_RADIANS
	var sq: float = sin(_t * SQUASH_HZ * tau) * SQUASH
	_body.scale = Vector2(_base_scale.x * (1.0 + sq), _base_scale.y * (1.0 - sq))

# ------------------------------------------------------------- read-only ------

func has_body() -> bool:
	return _body != null and is_instance_valid(_body)

func get_body_texture() -> Texture2D:
	return _body_tex
