extends RefCounted
## UiText — preload (res://scripts/ui/ui_text.gd).
##
## M42 (SB-M42-025) — the ONE translation/format seam for Home / Results / Home popups.
## Every user-facing string is a KEY. t(key, args) asks Godot's TranslationServer first
## (so shipping localizations are plain Translation resources) and falls back to the
## built-in English table. Values (SB amounts, Bot Parts, Gift Meter, streak rewards,
## Daily state, prices) are always passed in as live arguments — never baked into copy,
## and this seam never changes locked Economy V1 numbers.

const EN := {
	"HOME_PLAY": "PLAY",
	"HOME_CONTINUE_LEVEL": "CONTINUE · LEVEL %d",
	"HOME_START_LEVEL": "LEVEL %d",
	"HOME_RATIO": "%s/%s",
	"HOME_PLAYER_NAME_DEFAULT": "Scrubby",
	"HOME_AREA_TITLE": "WHISPERING PARK",
	"HOME_AREA_NUMBER": "AREA %d",
	"HOME_LEVEL_COMING_SOON": "Level %d is coming soon.",
	"HOME_LEVELS_UNAVAILABLE": "Levels unavailable (%s).",
	"HOME_LOADING": "Loading...",
	"HOME_SAVE_BLOCKED": "Save data is from a newer version. Update the game to continue.",
	"HOME_PROFILE_LINE": "LEVEL %d · %s",
	"HOME_BOT_PARTS": "BOT PARTS %s/%s",
	"HOME_ROBOT_READY": " · ROBOT READY",
	"HOME_GIFT_METER": "GIFT METER %s/%s · %s",
	"HOME_GIFT_NEXT": "NEXT GIFT AT %s",
	"HOME_GIFT_CYCLE_COMPLETE": "CYCLE COMPLETE",
	"HOME_CURRENCY_SB": "SB",
	"HOME_TRACK_AMOUNT": "+%s",
	"HOME_TRACK_WIN": "WIN %s",
	"HOME_TRACK_WIN_NOW": "WIN %s · NOW",
	"HOME_SC_WIN_STREAK": "WIN STREAK",
	"HOME_SC_GIFT_BAR": "GIFTS",
	"HOME_SC_COLLECTION": "COLLECTION",
	"HOME_SC_SHOP": "SHOP",
	"HOME_SC_DAILY": "DAILY",
	"HOME_SC_TASKS": "TASKS",
	"HOME_SC_CARDS_EXCHANGE": "CARDS EXCHANGE",
	"HOME_SC_NO_ADS": "NO ADS",
	"HOME_NAV_EVENTS": "EVENTS",
	"HOME_NAV_ROBOTS": "ROBOTS",
	"HOME_NAV_HOME": "HOME",
	"HOME_NAV_LEADERBOARD": "RANKS",
	"HOME_NAV_SETTINGS": "SETTINGS",
	"HOME_COMING_LATER": "Coming later",
	"POPUP_CLOSE": "CLOSE",
	"POPUP_CLAIM": "CLAIM",
	"GIFTS_TITLE": "GIFTS",
	"GIFTS_ROW": "GIFT %s · %s",
	"GIFTS_EMPTY": "No gifts to claim. Win levels in a row to fill the Gift Meter.",
	"GIFTS_READ_ONLY": "Claims are unavailable while the save is read-only.",
	"CARDS_TITLE": "CARDS EXCHANGE",
	"CARDS_ROW": "%s · x%s duplicate(s) · %s SB",
	"CARDS_EMPTY": "No duplicate cards yet.",
	"CARDS_NOTE": "%s duplicate card(s) worth %s SB. Exchange them in the Collection (coming later).",
	"DAILY_TITLE": "DAILY REWARDS",
	"DAILY_ROW": "DAY %d · %s%s",
	"DAILY_TODAY": " · TODAY",
	"DAILY_CLAIMED_TODAY": " · CLAIMED TODAY",
	"DAILY_STREAK": "Login streak: %s day(s).",
	"REWARD_ITEM": "%s x%s",
	"REWARD_scrub_bucks": "SB",
	"REWARD_bot_parts": "Bot Parts",
	"REWARD_standard_card_packs": "Card Pack",
	"REWARD_premium_card_packs": "Premium Pack",
	"REWARD_random_booster_charges": "Random Booster",
	"REWARD_selected_booster_charges": "Booster of choice",
	"REWARD_guaranteed_new_cards": "New Card",
	"RESULTS_WON": "LEVEL COMPLETE",
	"RESULTS_LOST": "LEVEL FAILED",
	"RESULTS_ERROR": "SOMETHING WENT WRONG",
	"RESULTS_LEVEL": "Level %d",
	"RESULTS_CONTINUE": "CONTINUE",
	"RESULTS_RETRY": "RETRY",
	"RESULTS_HOME": "HOME",
	"RESULTS_FIRST_CLEAR_SB": "First clear +%s SB",
	"RESULTS_STREAK_SB": "Win Streak %s · +%s SB",
	"RESULTS_BOT_PARTS": "+%s Bot Parts",
	"RESULTS_GIFT_METER": "Gift Meter %s/%s",
	"RESULTS_GIFT_READY": "Gift ready! Claim it in Gifts.",
	"RESULTS_CARDS": "+%s Card(s)",
	"RESULTS_ALREADY_CLEARED": "Already cleared · no progression reward",
	"RESULTS_NEXT_UNAVAILABLE": "Level %d is coming soon.",
	"GP_BUBBLE_HEADLINE": "LET'S CLEAN THIS MESS!",
	"GP_BUBBLE_INSTRUCTION": "Tap a batch below to send the Scrubbots.",
	"POPUP_BUSY": "Please wait...",
	"PAUSE_TITLE": "PAUSED",
	"PAUSE_RESUME": "RESUME",
	"PAUSE_RESTART": "RESTART",
	"PAUSE_HOME": "HOME",
	"RESTART_TITLE": "RESTART LEVEL?",
	"LEAVE_TITLE": "LEAVE LEVEL?",
	"CONSEQ_FREE": "You haven't made a move yet, so no Heart or Win Streak is lost.",
	"CONSEQ_LOSS_INTRO": "This counts as a loss:",
	"CONSEQ_HEART": "-1 Heart (%s → %s)",
	"CONSEQ_STREAK": "Win Streak %s resets to 0",
	"CONFIRM_RESTART": "RESTART",
	"CONFIRM_LEAVE": "LEAVE",
	"CONFIRM_KEEP_PLAYING": "KEEP PLAYING",
	"CONFIRM_OK": "OK",
	"CONFIRM_CANCEL": "CANCEL",
	"REWARD_TITLE": "YOU GOT",
	"REWARD_OK": "GREAT!",
	"INSUFFICIENT_TITLE": "NOT ENOUGH SB",
	"INSUFFICIENT_BODY": "%s costs %s SB.",
	"INSUFFICIENT_BALANCE": "You have %s SB · %s SB short",
	"INSUFFICIENT_SHOP": "GET SCRUB BUCKS",
	"NETWORK_TITLE": "NO CONNECTION",
	"NETWORK_BODY_REWARDED_AD": "Videos need an internet connection. Check it and try again.",
	"NETWORK_BODY_STORE": "The store needs an internet connection. Check it and try again.",
	"NETWORK_BODY_CLOUD": "Cloud save needs an internet connection. Check it and try again.",
	"NETWORK_BODY_LIVE_EVENT": "Events need an internet connection. Check it and try again.",
	"NETWORK_RETRY": "TRY AGAIN",
	"BUSY_TITLE": "ONE MOMENT",
	"FEEDBACK_SUCCESS": "SUCCESS!",
	"FEEDBACK_FAILURE": "THAT DIDN'T WORK",
	"FEEDBACK_REASON": "Nothing was spent. (%s)",
	"FEEDBACK_OK": "OK",
	"LIFE_TITLE": "LIFE",
	"LIFE_HEARTS": "%s / %s Hearts",
	"LIFE_NEXT_IN": "Next life in:",
	"LIFE_FULL": "Hearts full!",
	"LIFE_FULL_NOTE": "Your Hearts are full. Go play!",
	"LIFE_BOUGHT": "Hearts: %s",
	"LIFE_REWARDED": "+1 Heart!",
	"LIFE_CHEER": "Keep going! You're doing great!",
	"LIFE_REFILL_FULL": "FULL",
	"LIFE_ITEM_HEART_PLUS_ONE": "+1 Heart",
	"LIFE_ITEM_HEART_REFILL": "Full refill",
	"ACQ_BALANCE": "You have %s SB",
	"ACQ_PRICE_SB": "%s SB",
	"ACQ_NOT_ENOUGH": "Not enough Scrub Bucks.",
	"ACQ_REASON_ALREADY_FULL": "Your Hearts are already full.",
	"ACQ_REASON_FAILED": "That didn't work. Nothing was spent.",
	"REWARDED_FREE": "FREE",
	"REWARDED_UNAVAILABLE": "NO VIDEO",
	"REWARDED_UNAVAILABLE_NOTE": "Free videos aren't available right now.",
	"REWARDED_LOADING": "Loading video...",
	"REWARDED_NO_GRANT": "No reward: %s",
	"REWARDED_REASON_CANCELLED": "the video was closed.",
	"REWARDED_REASON_SKIPPED": "the video was skipped.",
	"REWARDED_REASON_TIMEOUT": "the video took too long.",
	"REWARDED_REASON_ALREADY_FULL": "your Hearts are already full.",
	"REWARDED_REASON_FAILED": "the video couldn't finish.",
	"BOOSTER_NAME_PLUS_ONE_SLOT": "+1 SLOT",
	"BOOSTER_NAME_RANDOM": "RANDOM",
	"BOOSTER_NAME_SELECTOR": "SELECTOR",
	"BOOSTER_NAME_TORNADO": "TORNADO",
	"BOOSTER_EFFECT_PLUS_ONE_SLOT": "Adds a sixth slot for this level.",
	"BOOSTER_EFFECT_RANDOM": "Shuffles the batches still waiting in the supply.",
	"BOOSTER_EFFECT_SELECTOR": "Sends any safe batch straight to an empty slot.",
	"BOOSTER_EFFECT_TORNADO": "Clears every cell of one colour.",
	"BOOSTER_OWNED": "Owned: %s",
	"BOOSTER_PICK_BATCH": "Choose a batch:",
	"BOOSTER_PICK_COLOR": "Choose a colour:",
	"BOOSTER_SAFETY_PLUS_ONE_SLOT": "+1 Slot is already active this level.",
	"BOOSTER_SAFETY_RANDOM": "Random can't be used safely right now.",
	"BOOSTER_SAFETY_SELECTOR": "No batch can move safely right now. Free a slot first.",
	"BOOSTER_SAFETY_TORNADO": "There is no colour to clear right now.",
	"BOOSTER_USE_OWNED": "USE (%s OWNED)",
	"BOOSTER_USE_SB": "USE · %s SB",
	"BOOSTER_NOT_USED": "Couldn't use it right now. Nothing was spent.",
	"BOOSTER_CHARGE_SAVED": "Booster saved! Use it when it fits.",
	"RESULTS_CLEAN_NEXT": "CLEAN NEXT",
	"JOURNEY_CAPTION": "CLEANING JOURNEY · %s/%s",
	"NEXT_CLEANUP_TITLE": "NEXT CLEANUP",
	"NEXT_CLEANUP_LEVEL": "LEVEL %d",
	"NEXT_CLEANUP_FACTS": "%s · %s colours",
	"NEXT_CLEANUP_SOON": "Coming soon",
	"DIFFICULTY_EASY": "EASY",
	"DIFFICULTY_MEDIUM": "MEDIUM",
	"DIFFICULTY_HARD": "HARD",
	"DIFFICULTY_VERY_HARD": "VERY HARD",
	"FAIL_HEARTS": "Hearts %s → %s",
	"FAIL_STREAK_RESET": "Win Streak %s ended",
	"FAIL_ENCOURAGE": "So close! Give it another try.",
	"NAH_TITLE": "NEED A HAND?",
	"NAH_SUBTITLE": "A little boost can help!",
	"NAH_BENEFIT_PLUS_ONE_SLOT": "One more slot for your batches",
	"NAH_BENEFIT_RANDOM": "Shuffles the waiting batches",
	"NAH_BENEFIT_SELECTOR": "Pick any safe batch you need",
	"NAH_BENEFIT_TORNADO": "Clears one whole colour",
	"NAH_BUY": "BUY · %s SB",
	"NAH_WATCH": "WATCH AD",
	"NAH_AD_UNAVAILABLE": "No video right now",
	"NAH_OWNED": "Owned: %s",
	"NAH_OWNED_READY": "Ready for your next try!",
	"NAH_BOUGHT": "%s saved for your next try!",
	"NAH_BUBBLE": "You've been trying really hard! Take a little boost and try again.",
	"NAH_NO_GUARANTEE": "Boosters help — the win is still yours to make.",
	"SHOP_TITLE": "SHOP",
	"SHOP_SOON": "The Shop is opening soon. Nothing was charged.",
	"SHOP_FOR": "Needed for: %s (%s SB)",
	"SHOP_BACK": "BACK",
	"SPEED_TITLE": "2x SPEED",
	"SPEED_EXPLAIN": "Scrubbots move twice as fast. Switch 1x/2x freely while it's active.",
	"SPEED_NONE": "2x is not active",
	"SPEED_LEVEL_ACTIVE": "Active for this level",
	"SPEED_TIMED_ACTIVE": "Active · %s left",
	"SPEED_OFFER": "%s
%s SB",
	"SPEED_OFFER_ACTIVE": "%s
ACTIVE",
	"SPEED_UNAVAILABLE": "Purchase unavailable (%s).",
	"SPEED_ITEM": "2x %s",
	"SPEED_LABEL_LEVEL": "THIS LEVEL",
	"SPEED_LABEL_MINUTES": "%d MIN",
	"PACK_STANDARD_TITLE": "STANDARD PACK",
	"PACK_PREMIUM_TITLE": "PREMIUM PACK",
	"PACK_TAP_OPEN": "Tap to open",
	"PACK_CARD_NEW": "NEW",
	"PACK_CARD_DUPLICATE": "DUPLICATE",
	"PACK_CARD_FIRST_COPY": "FIRST COPY",
	"PACK_CARD_EXTRAS": "EXTRAS x%d",
	"PACK_TAP_COLLECT": "Tap to collect your cards",
	"RARITY_COMMON": "COMMON",
	"RARITY_RARE": "RARE",
	"RARITY_EPIC": "EPIC",
	"RARITY_LEGENDARY": "LEGENDARY",
	"CEREMONY_CONTINUE": "CONTINUE",
	"CEREMONY_ROW_SB": "+%s Scrub Bucks",
	"CEREMONY_ROW_BOT_PARTS": "+%s Bot Parts",
	"CEREMONY_ROW_STANDARD_PACK": "+%s Standard Card Pack",
	"CEREMONY_ROW_PREMIUM_PACK": "+%s Premium Card Pack",
	"CEREMONY_ROW_RANDOM_BOOSTER": "+%s Random Booster",
	"CEREMONY_ROW_BOOSTER_CHOICE": "+%s Booster of your choice",
	"CEREMONY_ROW_NEW_CARD": "+%s guaranteed NEW card",
	"CEREMONY_ROW_HEART": "+%s Heart",
	"CEREMONY_SET_TITLE": "SET COMPLETE!",
	"CEREMONY_SET_NAME": "Set %d · %s",
	"CEREMONY_SET_PROGRESS": "%d / %d cards",
	"CEREMONY_SET_COMMITTED": "Set reward already added to your account.",
	"CEREMONY_MASTER_TITLE": "MASTER COLLECTION!",
	"CEREMONY_MASTER_SETS": "All %d sets complete",
	"CEREMONY_MASTER_ONCE": "One-time master reward",
	"CEREMONY_MASTER_COMMITTED": "Master reward already added to your account.",
	"CEREMONY_ROBOT_TITLE": "NEW ROBOT UNLOCKED!",
	"CEREMONY_ROBOT_PARTS_LEFT": "Bot Parts left: %s",
	"CEREMONY_ROBOT_EQUIP": "EQUIP %s",
	"CEREMONY_ROBOT_KEEP": "KEEP CURRENT",
	"CEREMONY_GIFT_TITLE": "GIFT METER %s!",
	"CEREMONY_GIFT_MILESTONE": "Milestone %s / %s",
	"CEREMONY_GIFT_FALLBACK": "If every card is already owned, the NEW card becomes %s Scrub Bucks.",
	"CEREMONY_GIFT_CLAIM_IN_BAR": "Ready to claim in the Gift Bar.",
	"CEREMONY_GIFT_CLAIMED": "Already claimed from the Gift Bar.",
	"CEREMONY_FEATURE_TITLE": "NEW FEATURE!",
	"CEREMONY_FEATURE_GOT_IT": "GOT IT",
	"CEREMONY_WORLD_BODY": "New cleaning area ready.",
	"RESULTS_GIFT_METER_NEXT": "Gift Meter %s/%s · next gift at %s",
	"GIFTS_PROGRESS": "Gift Meter %s/%s · next gift at %s",
	"SHOP_SECTION_HEARTS": "HEARTS",
	"SHOP_SECTION_BOOSTERS": "BOOSTERS",
	"SHOP_SECTION_SPEED": "2X SPEED",
	"SHOP_SECTION_SB": "SCRUB BUCKS",
	"SHOP_SECTION_NO_ADS": "NO ADS",
	"SHOP_SB_PACKS": "Scrub Bucks packs",
	"SHOP_NO_ADS": "Remove ads",
	"SHOP_SB_VALUE": "%s SB",
	"SHOP_PRICE": "%s SB",
	"SHOP_UNAVAILABLE": "UNAVAILABLE",
	"SHOP_NEED_MORE": "Need %s more SB",
	"SHOP_SPEED_ACTIVE": "2x active · %s left",
	"SHOP_SPEED_IN_LEVEL": "Buy it during a level.",
	"SHOP_STORE_LATER": "Available when the store opens.",
	"SHOP_CONFIRM_TITLE": "CONFIRM PURCHASE",
	"SHOP_CONFIRM_BODY": "Buy %s for %s SB?",
	"SHOP_CONFIRM_BUY": "BUY",
	"SHOP_BOUGHT": "%s added!",
	"SHOP_BACK_TO": "BACK TO %s",
	"SHOP_CLOSE": "CLOSE",
	"COLLECTION_TITLE": "COLLECTION",
	"COLLECTION_OPEN_EXCHANGE": "CARDS EXCHANGE",
	"COLLECTION_SUMMARY": "%d / %d cards · %d / %d sets complete",
	"COLLECTION_SET_ROW": "Set %d · %s",
	"COLLECTION_VIEW": "VIEW",
	"COLLECTION_PROGRESS": "%d / %d cards",
	"COLLECTION_REWARD": "Set reward: +%s SB +%s Bot Parts",
	"COLLECTION_CLAIMED": "· CLAIMED",
	"COLLECTION_NOT_CLAIMED": "· on completion",
	"COLLECTION_MASTER_ROW": "Master Collection %d / %d sets · +%s SB +%s Bot Parts %s",
	"COLLECTION_NOT_FOUND": "Not found yet",
	"COLLECTION_DETAILS": "DETAILS",
	"COLLECTION_OWNED": "Owned x%d",
	"COLLECTION_PROTECTED": "First copy is protected (never exchanged).",
	"COLLECTION_NO_EXTRAS": "No extras to exchange.",
	"COLLECTION_VALUE": "%s SB per extra copy",
	"COLLECTION_EXCHANGE_ONE": "EXCHANGE 1 · %s SB",
	"COLLECTION_EXCHANGE_CARD_ALL": "EXCHANGE %d · %s SB",
	"COLLECTION_EXCHANGE_ROW": "%s · %s · EXTRAS x%d · %s SB",
	"COLLECTION_EXCHANGE_TOTAL": "Total: %s SB",
	"COLLECTION_EXCHANGE_ALL": "EXCHANGE ALL EXTRAS · %s SB",
	"COLLECTION_CONFIRM_TITLE": "CONFIRM EXCHANGE",
	"COLLECTION_CONFIRM_CARD": "Exchange %d x %s for %s SB? Your first copy stays.",
	"COLLECTION_CONFIRM_ALL": "Exchange every extra copy for %s SB? Every first copy stays.",
	"COLLECTION_CONFIRM_YES": "EXCHANGE",
	"COLLECTION_EXCHANGED": "+%s SB from the exchange.",
	"COLLECTION_PITY_NEXT": "NEW CARD GUARANTEED NEXT PACK",
	"ROBOTS_TITLE": "ROBOTS",
	"ROBOTS_PARTS": "Bot Parts %s / %s toward %s",
	"ROBOTS_ALL_UNLOCKED": "All robots unlocked · Bot Parts %s",
	"ROBOTS_OVERFLOW": "+%s Bot Parts carry over after unlocking",
	"ROBOTS_ACTIVE": "ACTIVE",
	"ROBOTS_UNLOCKED": "UNLOCKED",
	"ROBOTS_LOCKED": "LOCKED",
	"ROBOTS_EQUIP": "EQUIP",
	"ROBOTS_UNLOCK": "UNLOCK %s",
	"ROBOTS_NOTE_ACTIVE": "Your active robot.",
	"ROBOTS_NOTE_NEXT": "Next unlock · %s Bot Parts",
	"ROBOTS_NOTE_LOCKED": "Unlocks in order.",
	"ROBOTS_DETAIL_NEED": "Needs %s Bot Parts in total (you have %s)",
	"ROBOTS_DETAIL_EARNED": "Bot Parts are earned by playing. They cannot be bought.",
	"ROBOTS_PERK_META": "Perks are rewards bonuses only. They never change a puzzle.",
	"TASKS_TITLE": "TASKS",
	"TASKS_SUBTITLE": "Today's three Scrub Orders",
	"TASK_NONE": "No order available today",
	"TASK_WIN_ONE": "Win 1 level",
	"TASK_WIN_N": "Win %s levels",
	"TASK_WIN_NO_BOOSTER": "Win a level without using a booster",
	"TASK_WIN_CLASS": "Win a %s or harder level",
	"TASK_CLEAR_CELLS": "Clear %s pixels",
	"TASK_PROGRESS": "%s / %s",
	"TASK_CLAIMED": "CLAIMED",
	"TASK_REWARD_SB": "%s SB",
	"TASKS_BOX": "Finish all 3 orders (%s/%s) to open the ScrubBox",
	"TASKS_BOX_OPEN": "OPEN",
	"TASKS_BOX_OPENED": "ScrubBox opened today. New orders tomorrow.",
	"TASKS_RESET_NOTE": "New orders every day.",
	"SCRUBBOX_TITLE": "SCRUBBOX",
	"SCRUBBOX_EARNED": "Earned by finishing all three orders.",
	"POPUP_COLLECT": "COLLECT",
	"DAILY_CONSECUTIVE": "Consecutive Login Days: %s",
	"DAILY_DAY": "DAY %d",
	"DAILY_STATE_CLAIMED": "CLAIMED",
	"DAILY_CARD_TODAY": "TODAY",
	"DAILY_CARD_CLAIMED_TODAY": "CLAIMED TODAY",
	"DAILY_RULE": "Claim once per day. Missing a day restarts at Day 1.",
	"DAILY_CYCLE_DONE": "5-day cycle complete! Day 1 starts again tomorrow.",
}

## Keyed text for `prefix + reason`, falling back to `prefix + FAILED` for an unknown code.
static func reason(prefix: String, code: String) -> String:
	var key := prefix + code.to_upper()
	return t(key if EN.has(key) else prefix + "FAILED")

## Translated (or English fallback) copy for `key`, formatted with `args`.
static func t(key: String, args: Array = []) -> String:
	var tr_text := String(TranslationServer.translate(key))
	var text: String = tr_text if tr_text != key else String(EN.get(key, key))
	if args.is_empty():
		return text
	return text % args

## Integer with thousands grouping (single seam; a locale-aware separator can replace it).
static func num(n: int) -> String:
	var neg := n < 0
	var d := str(absi(n))
	var out := ""
	while d.length() > 3:
		out = "," + d.substr(d.length() - 3) + out
		d = d.substr(0, d.length() - 3)
	return ("-" if neg else "") + d + out

## Human text for a canonical reward bundle, e.g. {"scrub_bucks": 100} -> "SB x100".
static func reward_text(rewards: Dictionary) -> String:
	var parts: Array = []
	var keys: Array = rewards.keys()
	keys.sort()
	for k in keys:
		if int(rewards[k]) > 0:
			parts.append(t("REWARD_ITEM", [t("REWARD_" + String(k)), num(int(rewards[k]))]))
	return ", ".join(parts)
